# Site wide configuration

title: "Xaba Cadabra"
description: "Xaba Cadabra è un blog colmo di recensioni e speculazioni caustiche riguardo Videogiochi, Serie TV, Fumetti e tutte quelle robe nerd."
logo: logo.png # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: it
url: http://xabacadabra.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
  
# Site owner
owner:
  name: "Andrea Xab Corinti"
  email: xabarasff@gmail.com
  twitter: xabaras89
  google: 110802041334218664272
    ad-client:
    ad-slot:
  bio: "A (web) world citizen. Svezzato da Final Fantasy, Dylan Dog, Web 1.5, Bakunin e Faith No More."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: xabacadabra
  google_analytics: UA-71672759-1

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
