# Site wide configuration

title: "Xaba Cadabra"
description: "Recensioni che offrono una caustica visione su Videogiochi, Serie TV, Fumetti e tutte quelle cose da nerd."
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: //xabacadabra.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: "Andrea Xab Corinti"
  email: xabarasff@gmail.com
  twitter: xabaras89
  google:
    ad-client:
    ad-slot:
  bio: "Final Fantasy, Dylan Dog, Web 1.5, Bakunin e Faith No More. In TV tifa Gazebo, nel basket Cantù. Ama Lubuntu e venera Neil Gaiman."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: xabaras89


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
