# Site wide configuration

title: "Xaba Cadabra"
description: "Xaba Cadabra è un blog colmo di recensioni e speculazioni caustiche riguardo Videogiochi, Serie TV, Fumetti e tutte quelle robe nerd."
logo: logo.png # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: it
url: https://xabacadabra.com
#url: http://127.0.0.1:4000/ 
feed:
 path: atom.xml

social:
  name                   : "Andrea Corinti"
  links:
    - "https://twitter.com/Xabaras89"
    - "https://www.facebook.com/galbadia"
    - "https://www.instagram.com/xabaras89/"
    - "https://github.com/xabacadabra"
    - "https://plus.google.com/u/0/+AndreaXabCorinti/posts"

# Compress Html

compress_html:
  clippings: all
  ignore:
    envs: development    

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true

# Repository e Staticman

repository: "Xabacadabra/Xabacadabra.github.io"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : "Nuovo Commento!"
  filename               : commento-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "unien28601"
  
# Site owner
owner:
  name: "Andrea Xab Corinti"
  email: xabarasff@gmail.com
  twitter: xabaras89
  google:
    ad-client: ca-pub-1505772893706847
    ad-slot: 1190854446
  bio: "A (web) world citizen."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: xabacadabra
  google_analytics: UA-71672759-1

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
include: [".well-known"]